### PR TITLE
Packer introduction.

### PR DESCRIPTION
**Pull request by st4nson**
**WIP DO NOT MERGE** 

Packer (packer.io) is used to create SWAN cached image.

Fixes issue ...

Summary of changes:
- 
- 
- 

Testing done:
-

### CODE REVIEW

**Comment by iwankgb** [comment]
@st4nson - how can I use Packer JSON file?

**Comment by st4nson** [comment]
@iwankgb README.md will describe everything.

**Comment by iwankgb** [comment]
@st4nson any chance to add it? There is also a need to update the branch from master.

**Comment by iwankgb** [comment]
Closing stale PR.

**Pull request closed without merging**
