### PR TITLE
Fixed Etcd package installation

### PR DESCRIPTION
**Pull request by Dual2Core**
Fixes issue where etcd did not install during execution of `provision_experiment_environment.sh`.

Summary of changes:
- Etcd version specification deleted

Testing done:
- Script executed on VMs and successfully installed etcd.

### CODE REVIEW

**Comment by Dual2Core** [comment]
run integration tests

**Comment by mpatelcz** [comment]
run integration tests

**Comment by Dual2Core** [comment]
run integration tests

**Comment by iwankgb** [comment]
This PR is inactive for nearly two months.

**Pull request closed without merging**
