### PR TITLE
Getting rid of assignment with no effect

### PR DESCRIPTION
**Pull request by iwankgb**
Fixes issue of ineffectual assignments in the code

Summary of changes:
- fixed variable assignments that had no effect- 

Testing done:
- all existing tests should pass

### CODE REVIEW

**Comment by iwankgb** [comment]
run integration tests

**Comment by skonefal** [comment]
run integration tests

**Comment by skonefal** [comment]
run integration tests

**Comment by iwankgb** [comment]
It does not seem to be work that is going to be finished in foreseeable future.

**Pull request closed without merging**
