### PR TITLE
Fixing issues with K8s 1.7.x

### PR DESCRIPTION
**Pull request by iwankgb**
Fixes issue of unstable Kubernetes-related tests

Summary of changes:
- Upgrading Docker to 17.06.1 and Kubernetes to 1.7.4
- Getting rid of `UniqueConfig()` - it was the *real* issue as sometimes there were two clusters running in the same time. Kudos go to @flyingcougar for identifying it!
- Making sure that all artifacts are deleted when K8s cluster is eventually stopped
- Setting the logs up will suffice - we do not want to indicate that pod is ready

Testing done:
- some tests modiefied
- periodical tests on Jenkins should stop failing!

### CODE REVIEW

**Comment by iwankgb** [comment]
run integration tests

**Comment by iwankgb** [comment]
run integration tests

**Comment by iwankgb** [comment]
run integration tests

**Comment by iwankgb** [comment]
run integration tests

**Comment by iwankgb** [comment]
run integration tests

**Comment by iwankgb** [comment]
run integration tests

**Comment by iwankgb** [comment]
run integration tests

**Comment by iwankgb** [comment]
run integration tests

**Comment by flyingcougar** [comment]
lgtm

**Pull request merged**
