### PR TITLE
Removing unused variables and struct fields

### PR DESCRIPTION
**Pull request by iwankgb**
Fixes issue of package variables and struct fields that were not being used.

Summary of changes:
- deleted few variables
- deleted one struct field

Testing done:
- all existing tests should pass

### CODE REVIEW

**Comment by iwankgb** [comment]
run integration tests

**Comment by skonefal** [comment]
run integration tests

**Comment by skonefal** [comment]
@iwankgb in some cases, gometalinter spawns too much threads which effectively DoS system.

**Comment by iwankgb** [comment]
run integration tests

**Comment by iwankgb** [comment]
I takes about 720 seconds for `test_lint` to finish. We should discuss if this PR is worth being merged.

**Comment by iwankgb** [comment]
run integration tests

**Comment by skonefal** [comment]
@iwankgb we might want to have separate "extended lint" as an additional target so that it will run parallel to integration test. It might also be faster on AWS instead of travis.

**Pull request merged**
