### PR TITLE
Using Go 1.9

### PR DESCRIPTION
**Pull request by iwankgb**
Fixes issue of strong urge to upgrade Go version.

Summary of changes:
- Go version upgraded to 1.9
- New AMI created

Testing done:
- all existing tests should pass.

### CODE REVIEW

**Comment by iwankgb** [comment]
run integration tests

**Comment by iwankgb** [comment]
run integration tests

**Comment by mpatelcz** [comment]
run integration tests

**Comment by mpatelcz** [comment]
run integration tests

**Pull request merged**
